
SHELL := /bin/bash

# **** INPUT VARIABLES ***** #
CLUSTER_NAME ?= 
API_SERVER_IP ?=
K8S_VERSION ?=
ISTIO_VERSION ?=


# Setup the node with pre-sets to install required packages
.PHONY: bootstrap
bootstrap:
