apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "enable-jwt"
spec:
  targets:
  - name: "productpage"
  peers:
  - mtls: {}
  origins:
  - jwt:
      issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.0/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
