apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: review-see-rating-viewer
  namespace: default
spec:
  rules:
  - services: ["ratings.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-review-ratings-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
    properties:
      version: "v3"
  roleRef:
    kind: ServiceRole
    name: "review-see-rating-viewer"
