apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: details-viewer
  namespace: default
spec:
  rules:
  - services: ["productpage.default.svc.cluster.local", "details.default.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-details-viewer
  namespace: default
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "details-viewer"
