apiVersion: "authenication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: "default"
  namespace: "default"
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "disable--mtls"
  namespace: "default"
spec:
  host: "*.default.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: PERMISSIVE
