version: '3'
services:
  netdata:
    image: "netdata:1.0"
    container_name: netdata
    network_mode: "host"
    env_file: ./netdata.env
    restart: always
    stdin_open: True
    tty: True
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
